output_directory: "/oak/stanford/groups/smontgom/shared/UDN/Analysis/FRASER/pipelines/FRASER_snakemake/output/FRASER_Sep_13"
metadata_file: "/oak/stanford/groups/smontgom/shared/UDN/FRASER_analysis/files/2017to2022_metadata.tsv"
bam_file_directory: ""
data_type: "Blood"
mig_file: "/oak/stanford/groups/smontgom/shared/UDN/ReferenceFiles/Minor_Intron_Database/Homo_sapiens_gene.csv"
input_directory: "/oak/stanford/groups/smontgom/shared/UDN/Analysis/FRASER/pipelines/FRASER_snakemake/data/FRASER_Sept_13"
file_list: "/oak/stanford/groups/smontgom/shared/UDN/Analysis/FRASER/pipelines/FRASER_snakemake/config/symlink_blood.csv"