output_directory: "/home/maurertm/smontgom/shared/UDN/Analysis/Transcriptome_Wide_Splicing_Analysis/FRASER_snakemake_cleaned_github/data/test_output"
input_directory: "/home/maurertm/smontgom/shared/UDN/Analysis/Transcriptome_Wide_Splicing_Analysis/FRASER_snakemake_cleaned_github/data/test_data"
file_list: "/home/maurertm/smontgom/shared/UDN/Analysis/Transcriptome_Wide_Splicing_Analysis/FRASER_snakemake_cleaned_github/config/test_input.csv"
FRASER_type: "Both"
