/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD105_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD106_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD113_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD114_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD149_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD320run18_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD338run18_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD051_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD053_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD069_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD102_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD103_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD104_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD107_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD108_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD109_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD110_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD111_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD112_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD115_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD116_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD117_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD297_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD299_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD300_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD301_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD314_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD315_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD316_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD318_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD321_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD322_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD323_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD324_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD325_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD326_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD327_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD329_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD330_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD331_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD332_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD333_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD334_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD335_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD336_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD339_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD340_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD341_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD342_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD343_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD344_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD345_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD346_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD347_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD348_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD349_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD350_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD449_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD450_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD541_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD542_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD543_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD544_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD545_star_hg38_Aligned.sortedByCoord.out.bam
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD105_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD106_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD113_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD114_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD149_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD320run18_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD338run18_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD051_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD053_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD069_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD102_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD103_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD104_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD107_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD108_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD109_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD110_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD111_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD112_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD115_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD116_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD117_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD297_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD299_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD300_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD301_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD314_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD315_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD316_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD318_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD321_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD322_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD323_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD324_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD325_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD326_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD327_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD329_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD330_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD331_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD332_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD333_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD334_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD335_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD336_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD339_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD340_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD341_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD342_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD343_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD344_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD345_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD346_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD347_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD348_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD349_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD350_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD449_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD450_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD541_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD542_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD543_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD544_star_hg38_Aligned.sortedByCoord.out.bam.bai
/oak/stanford/groups/smontgom/shared/UDN/Output/hg38/STAROutput/Reindexed_and_Filtered_UDN_January2024/genome/RD545_star_hg38_Aligned.sortedByCoord.out.bam.bai